FROM python:3.12

WORKDIR /app

RUN pip3 install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
RUN pip3 install --no-cache-dir -e .

EXPOSE 8090

VOLUME /data/repos
VOLUME /data/mirrors

ENTRYPOINT [ "olah-cli" ]

CMD ["--repos-path", "/repos"]
